### ISSUE TITLE
Menu items too tight on small screens.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#1]
Make sure the lines are a bit more spread out for easy tapping. Please make sure to test on your phone.

Example: http://lift.d.pr/aiAm

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
