### ISSUE TITLE
Opening the mobile menu pushes the hero text down. 

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#2]
The menu should overlay the content beneath it, including the hero area.

Bug visual: http://lift.d.pr/pPtH

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
