### ISSUE TITLE
Add hover state to social menu items

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#5]
Right now, there is no hover change of any kind. We need something there, even if it's just a color change on the text or background color change.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
