### ISSUE TITLE
Update page templates to match other theme standards.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#6]
All other themes have two templates that exist for utilizing Beaver Builder. One is a full-width page template called `Page Builder (No Header)` and the other is a full-width page template called `Page Builder` which contains a header area with a title and the header image represented to match the designs.

Please rename the existing template called `Page Builder` to `Page Builder (No Header)` and create the other template with the header image.

You can look at Ascension for an example of this.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
