### ISSUE TITLE
Make sure the left/right nav items don't extend beyond the content above and below.

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#8]
Current position: http://lift.d.pr/AYNh

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
