### ISSUE TITLE
Missing two widgetized sidebars

### ISSUE THREAD

**Issue by chriswallace** [LiftUX/escapade-theme#9]
I don't see the primary or secondary sidebar in this theme, they should be visible on single, archive, and blog pages.

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;e9pkmwH4&#x2F;24-escapade-travel-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Escapade (Travel Theme)</a>
